spring.application.name=MyWorks

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/todo_db
spring.datasource.username=todo_user
spring.datasource.password=todo_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=src/main/resources/db/migration/V1__init_schema.sql

spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
