apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-native-kafka
  namespace: auth-demo
  labels:
    app: notification-service-native-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service-native-kafka
  template:
    metadata:
      labels:
        app: notification-service-native-kafka
    spec:
      containers:
        - name: notification-service-native-kafka
          image: notification-service-native-kafka:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: kafka-connection-config
