kafka.bootstrap-servers=localhost:9092
kafka.topic.verification-codes=verification-codes
kafka.consumer.group-id=notification-service-native-kafka-group
kafka.consumer.auto-offset-reset=earliest
kafka.consumer.poll-timeout-ms=1000